import React from "react";
import { Row, Col } from 'antd';

import globalstyle from '../../style.module.css';

import PageseMetaTags from "../metaTags";
import BgBefore from "../breadcrumbs/bgBefore";
import BreadcrumbMenu from "../breadcrumbs/breadcrumbs";

const style = {padding: '50px 0' };

const Tools_TradersGlossary = () => {
  return( <div>
            <PageseMetaTags 
            title="Title"
            description="description"
            />
        <BgBefore />
        <BreadcrumbMenu />

    <div className={globalstyle.container}>

        <Row>
            <Col span={24} className="gutter-row">

            <div style={style}>


      <div>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><u><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>TRADER'S GLOSSARY</span></u></strong></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Here are some terms every trader should be familiar with</span></strong></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Day Trade:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;When a trader places an opening and closing trade on the same stock on the same day, they are making a day trade and are subject to special rules.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Professional Day Trader:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A professional day trader can informally be considered somebody who day trades for a living.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Swing Trading:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Swing traders will hold stocks for at least one night. These are very short-term investments.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Bull or Bullish:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;This term refers to a strong market of stocks moving up.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Bear or Bearish:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;This term refers to a weak market; this means traders think the price of stocks or a specific stock will be going down.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Initial Public Offering (IPO):</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;When a company floats an IPO, they sell a fixed number of shares of a particular company in the open market to raise money.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Float:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Float refers to the number of outstanding shares available for trade.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Share Buy Back:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A Share Buy Back program is when a company buys back shares that were sold during the IPO. By doing this, they are reducing the number of shares available for trading purposes in the market.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Secondary Offering:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A secondary offering is an offering that is given after the Initial Public Offering. A secondary offering will raise money for the company by selling more shares.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Beta:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Beta is a measure of the volatility—or systematic risk—a security or portfolio compared to the market as a whole.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Crossed Market:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A crossed market refers to a temporary situation where the bid price associated with a particular asset or security is higher than the asking price.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Dividend:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A dividend is money paid out to shareholders who hold shares of the company as a way of sharing the company's success.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Divergence:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;In day trading, divergence is a trading concept that forms on your trading bar chart and results from the price action of security moving in opposite directions.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Earnings Per Share:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Earnings Per Share (EPS) is a portion of a company's profit allocated to a person's stock share and is an essential metric for analysts.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Market Cap:&nbsp;</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Market Capitalisation is a measurement used to classify a company's size and is based on the market value of the total shares outstanding.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Merger:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Mergers are deals that unite two separate companies into a single new company.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Penny Stocks:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A penny stock typically refers to the stock of a small company.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Return on Investment (ROI):</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Return on investment (ROI) is a metric that measures profit or loss generated by an investment about the invested funds.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Shares Outstanding:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Shares outstanding refers to the stock of a company currently held by all shareholders, including restricted and institutional shares.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Market Trend:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Market trend represents the general direction in a market or security over a given period and can last from a couple of days to many months or years.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Volatility:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Volatility is a measure of the security's stability and is usually calculated as the standard deviation derived over a given period of time.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Support Level:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A support level is the price level whereby the demand for security is strong enough to prevent the decline in its price past it.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Resistance Level:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A resistance level is the price level at which the selling of a security is deemed healthy enough to eliminate the price increase.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Stock:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Stock is a type of asset that gives you ownership in a company, allowing you to claim the company's assets and earnings.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Price Target:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A price target is the projected price of a financial instrument provided by an analyst and used to determine under and overvalued stocks.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Recession:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A recession refers to when a country's economy experiences a decline due to different factors over a specific period of time.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>OTC Market:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The OTC or over-the-counter market allows for the trading of assets without the formal structure of official exchange and is considered risky.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Hard To Borrow:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The Hard to borrow list refers to an inventory of securities the brokerage firm cannot provide for short selling and is only available for buying.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Derivative:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Derivatives are securities with prices dependent on, or derived from, one or more separate underlying assets such as options or futures contracts.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Equity:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Equity refers to the ownership of assets after liabilities and debts have been settled, or it can refer to stock or ownership of shares in a public company.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Blue Chip:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Blue-chip stocks are companies that are often worth billions of dollars, pay dividends, and have a long history of reliable operations.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Bond:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A bond is a debt investment where investors loan funds to a corporate or government for a particular period of time at a variable or fixed interest rate.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Long Side Trading:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;When traders are "long" a stock, they are buying shares and expect the stock price to go up.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Price Average:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Price average is the average price of the stock that you have paid.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Short Side Trading:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Traders who are "short" on a stock are short-selling shares. As soon as they sell the shares, they profit from the sale; however, they must buy back the shares.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Borrowing:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;You must borrow shares from your broker to short. If your broker doesn't have shares available to borrow, you can't short the stock.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Covering:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;To close a short position, a trader must "cover" their position, this is, buying stocks to cover the shares they borrowed from their broker.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Short Interest:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Short interest refers to the number of shares all traders worldwide are currently holding as a short position against the stock.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Short Squeeze:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;This is when a stock suddenly starts moving up, and traders holding short positions start buying to cover their positions.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Margin:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;When a trader opens a broker account, they are given Margin. In addition to allowing you to trade on borrowed money, they also extend a line of credit to your account for trading.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Leverage Rate:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The rate that your cash deposit will be multiplied to give you total buying power.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Buying Power:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Your buying power is your cash balance plus your Margin.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Margin Rate:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The percentage a trader has to pay their broker in exchange for borrowing money.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Margin Call:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Traders who are issued a margin call are in debt to their broker. The broker will require you to repay the debt and force you to sell other assets to return the money.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Bid Price:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The Bid Price is the price traders are currently bidding on stock at.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Ask Price:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The Ask price is the price traders are currently asking to sell the stock at.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Spread:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The Spread is the difference between the Bid price and Ask price.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Market makers:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Market Makers create the spread. They are large institutional players that are both buyers and sellers of a stock.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Volume:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Volume is a measure of the number of shares traded.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Relative volume:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Relative volume shows how much volume a stock has compared to its average volume for the same period.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>A Thin Market:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A thin market means not many traders actively trade a particular stock.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>A Thick Market:&nbsp;</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Thickly-traded markets and stocks will be crowded with traders.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Circuit Breaker:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Stocks can be halted and paused from trading for several reasons. During circuit-breaker halts, traders cannot trade the stock in any way.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Slippage:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Slippage is the difference between the price you thought you would trade at and the price at which the trade went through.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Limit Orders:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A limit order is when you ask your broker to buy you shares and state the most you are willing to pay.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Stop Orders:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Stop orders are a versatile order used for getting in and out of trades. When you place a stop order, you are saying that you want to get in or out of a trade when prices hit your stop price.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>FOK Order:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;This is Fill or Kill, which means either you get your entire order filled or the order won't fill at all; this prevents partial orders.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>GTC Order:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;This is a Good Till Cancelled order. That means the order will stay on the broker's servers until you cancel it.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Trailing Stop:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;A trailing stop order is a stop order that allows the setting of the value as a percentage usually below the market price and will move as prices move.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Good Till Cancelled:&nbsp;</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>A Good Till Cancelled (GTC) order refers to a buy or sell request designed to last until the request is executed or canceled by the trader or broker.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Fundamental Analysis:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Fundamental Analysis is when a trader (or more often, an investor) looks at a company's fundamental metrics. This includes their annual and quarterly earnings per share, their book value (total value of company assets), their sector's strength, and the growth potential.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Technical Analysis:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Technical Analysis, in contrast to fundamental analysis, focuses solely on the stock price.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Line Charts:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Line charts simply plot a line. This can give a good understanding of price action over long periods of time, but it doesn't provide the necessary insight that traders require for shorter time periods.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Bar Charts:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Bar charts show the open price and the close price for any given period.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Candlestick Charts:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Candlestick charts include four pieces of information. The open price, the close price, the high of the period price, and the low of the period price.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Technical Indicators:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Technical indicators, or studies, help us interpret current price action.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Moving Averages:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Moving averages are a technical indicator that tells us the average price of a stock over time.&nbsp;</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Simple Moving Average:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Simple Moving Average (SMA) is an average price calculation on the closing price of a security over a period of time divided by the number of periods.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Volume Profile:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The volume profile refers to an advanced charting study used to show trading activity where volume is displayed at prices instead of over a specific time.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Standard Deviation:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Standard deviation is a statistical measure representing the rate of divergence from the mean in a data set and is used a lot in trading.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>On Balance Volume:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;On Balance Volume, a momentum indicator helps measure the buying and selling pressure in a stock or any other financial security with volume.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Opening Range Breakout:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;An opening range breakout is a relatively simple strategy that involves taking a position when price breaks above or below the previous candle, high or low.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Keltner Channel:</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;The Keltner Channel is a technical indicator that shows a central line for a moving average and channel lines below and above.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>Average Directional Index (ADX):</span></strong><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif', color: '#0E101A'}}>&nbsp;Average Directional Index is a technical indicator used to signify the strength of a trend and works best when a stock is trending.</span></p>
        <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '8.0pt', marginLeft: '0cm', lineHeight: '150%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify'}}><span style={{fontSize: '19px', lineHeight: '150%', fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
      </div>
 

            <div>
         </div>

 
      </div>


            </Col>
        </Row>

    </div>

  </div>
  )

};

export default Tools_TradersGlossary;